spring:
  datasource:
    hikari:
      connection-timeout: 600000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
    url: jdbc:postgresql://127.0.0.1:5432/backend_class
    username: postgres
    password: pass1234
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true